from __future__ import annotations

from pathlib import Path


DEFAULT_OLLAMA_BASE_URL = "http://127.0.0.1:11434"
DEFAULT_OLLAMA_MODEL = "gemma4:e4b"
DEFAULT_OLLAMA_TIMEOUT_SECONDS = 10.0

DEFAULT_CAPTURE_INTERVAL_MS = 500
DEFAULT_TARGET_LANGUAGE = "pt-BR"
DEFAULT_SOURCE_LANGUAGE = "auto"

DEFAULT_OVERLAY_OPACITY = 0.85
DEFAULT_OVERLAY_FONT_SIZE = 24

DEFAULT_DATABASE_PATH = Path("data") / "app.sqlite3"
